### ISSUE TITLE
Create,Delete,View Blog

### ISSUE THREAD

**Issue by Mann23** [Mann23/27-Programming-Club-FrontEnd#1]
Implement feature to Create,Delete or View Blogs

**Comment by ghost** [comment]
Structure of the blog functionality has been done in the commit https://github.com/Mann23/27-Programming-Club-FrontEnd/commit/4db219d170ac51153bec1d4a3544ba4f238e6b47.

**Comment by ghost** [comment]
Directory structure has been changed for better development workflow management in the commit https://github.com/Mann23/27-Programming-Club-FrontEnd/commit/14f87feac4e6fbfb92ccd50c21b050c5ace4f30f

**Comment by ghost** [comment]
Added demo data for further development in the commit https://github.com/Mann23/27-Programming-Club-FrontEnd/commit/ea34a94b359cacbc86fd45ae1a8f12b43d0bc337

**Comment by Mann23** [comment]
Do implement routing part in future.

**Comment by ghost** [comment]
I have converted some of the class components into functional components in order take the advantage of hooks, implemented the useState and useEffect hooks, created endpoints for fetching data from apis using axios, also made some ui changes in blog-card and view-blog component.

**Comment by Mann23** [comment]
Good. Generate your pull request on deploy  .So that i will merge the code with deployAndChange branch. I will merge and route the components there.

**Comment by ghost** [comment]
Okay 👍
